version: '3'

services:
  validexapp:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: validex-docker
    container_name: validexapp
    restart: always
    ports:
      - '${PORT}:${PORT}'
    environment:
      MONGODB: ${MONGODB}
      PORT: ${PORT}
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}

  db:
    image: mongo:5
    container_name: mongo-valiant
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGODB_DATABASE: nest-valiant
    volumes:
      - ./mongo:/data/db
